// <auto-generated />
using System;
using API_AnalyseSanguine.Context.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_AnalyseSanguine.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230214184440_ResultatValeurFloatToString")]
    partial class ResultatValeurFloatToString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_AnalyseSanguine.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hémostase"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hématologie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Analyse de biochimie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Routine d'urine"
                        });
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.Dossier", b =>
                {
                    b.Property<int>("IdDossier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDossier"), 1L, 1);

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Sexe")
                        .HasColumnType("tinyint");

                    b.HasKey("IdDossier");

                    b.ToTable("Dossiers");

                    b.HasData(
                        new
                        {
                            IdDossier = 1,
                            DateNaissance = new DateTime(2001, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Turgeon",
                            Prenom = "Victor",
                            Sexe = (byte)0
                        },
                        new
                        {
                            IdDossier = 2,
                            DateNaissance = new DateTime(2002, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Belval",
                            Prenom = "Jean-Philippe",
                            Sexe = (byte)0
                        });
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.Medecin", b =>
                {
                    b.Property<int>("IdMedecin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedecin"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedecin");

                    b.ToTable("Medecins");

                    b.HasData(
                        new
                        {
                            IdMedecin = 1,
                            Nom = "Banville",
                            Prenom = "Zacharie"
                        },
                        new
                        {
                            IdMedecin = 2,
                            Nom = "Bourque",
                            Prenom = "Yannick"
                        },
                        new
                        {
                            IdMedecin = 3,
                            Nom = "Langlais",
                            Prenom = "Jonathan"
                        },
                        new
                        {
                            IdMedecin = 4,
                            Nom = "Jetté",
                            Prenom = "Antony"
                        },
                        new
                        {
                            IdMedecin = 5,
                            Nom = "Denis",
                            Prenom = "Lucas"
                        },
                        new
                        {
                            IdMedecin = 6,
                            Nom = "Lagacé",
                            Prenom = "Mathilde"
                        },
                        new
                        {
                            IdMedecin = 7,
                            Nom = "Néron",
                            Prenom = "Alicia"
                        },
                        new
                        {
                            IdMedecin = 8,
                            Nom = "Godin",
                            Prenom = "Raphaelle"
                        },
                        new
                        {
                            IdMedecin = 9,
                            Nom = "Martinez",
                            Prenom = "Leonie"
                        },
                        new
                        {
                            IdMedecin = 10,
                            Nom = "Daneau",
                            Prenom = "Rose"
                        });
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.RequeteAnalyse", b =>
                {
                    b.Property<int>("IdRequete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRequete"), 1L, 1);

                    b.Property<string>("AnalyseDemande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CodeAcces")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateEchantillon")
                        .HasColumnType("datetime2");

                    b.Property<int>("DossierIdDossier")
                        .HasColumnType("int");

                    b.Property<int>("MedecinIdMedecin")
                        .HasColumnType("int");

                    b.Property<string>("NomTechnicien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRequete");

                    b.HasIndex("DossierIdDossier");

                    b.HasIndex("MedecinIdMedecin");

                    b.ToTable("RequeteAnalyses");

                    b.HasData(
                        new
                        {
                            IdRequete = 1,
                            AnalyseDemande = "",
                            CodeAcces = new Guid("4b5bea76-58ba-48b3-89a3-66fd582e314a"),
                            DateEchantillon = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DossierIdDossier = 1,
                            MedecinIdMedecin = 1,
                            NomTechnicien = "Matheo Boudreau"
                        },
                        new
                        {
                            IdRequete = 2,
                            AnalyseDemande = "",
                            CodeAcces = new Guid("720e7a4f-db39-4d33-8315-38b56d851131"),
                            DateEchantillon = new DateTime(2017, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DossierIdDossier = 1,
                            MedecinIdMedecin = 7,
                            NomTechnicien = "Jerome Frenette"
                        },
                        new
                        {
                            IdRequete = 3,
                            AnalyseDemande = "",
                            CodeAcces = new Guid("672afc48-29e6-4f8e-9cf5-06d2a12cb525"),
                            DateEchantillon = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DossierIdDossier = 1,
                            MedecinIdMedecin = 3,
                            NomTechnicien = "Clara Faubert"
                        },
                        new
                        {
                            IdRequete = 4,
                            AnalyseDemande = "",
                            CodeAcces = new Guid("5f952717-b349-4926-b35f-1c6d80ecf2d3"),
                            DateEchantillon = new DateTime(2014, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DossierIdDossier = 2,
                            MedecinIdMedecin = 10,
                            NomTechnicien = "Louis Truchon"
                        },
                        new
                        {
                            IdRequete = 5,
                            AnalyseDemande = "",
                            CodeAcces = new Guid("905c9ea1-c328-46c2-88a4-fa90ad5350fd"),
                            DateEchantillon = new DateTime(2006, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DossierIdDossier = 2,
                            MedecinIdMedecin = 4,
                            NomTechnicien = "Andreanne Pearson"
                        },
                        new
                        {
                            IdRequete = 6,
                            AnalyseDemande = "",
                            CodeAcces = new Guid("3774b1c2-a433-4b7d-b82b-8733b9b4633d"),
                            DateEchantillon = new DateTime(2009, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DossierIdDossier = 2,
                            MedecinIdMedecin = 9,
                            NomTechnicien = "Sabrina Beauvais"
                        });
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.ResultatAnalyse", b =>
                {
                    b.Property<int>("IdResultatAnalyse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultatAnalyse"), 1L, 1);

                    b.Property<int>("RequeteAnalyseIdRequete")
                        .HasColumnType("int");

                    b.Property<int>("TypeValeurIdTypeValeur")
                        .HasColumnType("int");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResultatAnalyse");

                    b.HasIndex("RequeteAnalyseIdRequete");

                    b.HasIndex("TypeValeurIdTypeValeur");

                    b.ToTable("ResultatAnalyses");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.TypeAnalyse", b =>
                {
                    b.Property<int>("IdTypeAnalyse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeAnalyse"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTypeAnalyse");

                    b.HasIndex("CategoryId");

                    b.ToTable("TypeAnalyses");

                    b.HasData(
                        new
                        {
                            IdTypeAnalyse = 1,
                            CategoryId = 1,
                            Nom = "TS"
                        },
                        new
                        {
                            IdTypeAnalyse = 2,
                            CategoryId = 1,
                            Nom = "To"
                        },
                        new
                        {
                            IdTypeAnalyse = 3,
                            CategoryId = 1,
                            Nom = "PTT"
                        },
                        new
                        {
                            IdTypeAnalyse = 4,
                            CategoryId = 1,
                            Nom = "PT"
                        },
                        new
                        {
                            IdTypeAnalyse = 5,
                            CategoryId = 1,
                            Nom = "TT"
                        },
                        new
                        {
                            IdTypeAnalyse = 6,
                            CategoryId = 1,
                            Nom = "Fibrinogène"
                        },
                        new
                        {
                            IdTypeAnalyse = 7,
                            CategoryId = 1,
                            Nom = "Facteur"
                        },
                        new
                        {
                            IdTypeAnalyse = 8,
                            CategoryId = 1,
                            Nom = "D-dimères"
                        },
                        new
                        {
                            IdTypeAnalyse = 9,
                            CategoryId = 1,
                            Nom = "fVW"
                        },
                        new
                        {
                            IdTypeAnalyse = 10,
                            CategoryId = 1,
                            Nom = "LA Screen"
                        },
                        new
                        {
                            IdTypeAnalyse = 11,
                            CategoryId = 1,
                            Nom = "Anti-Xa"
                        },
                        new
                        {
                            IdTypeAnalyse = 12,
                            CategoryId = 1,
                            Nom = "Prt C"
                        },
                        new
                        {
                            IdTypeAnalyse = 13,
                            CategoryId = 1,
                            Nom = "Prt S"
                        },
                        new
                        {
                            IdTypeAnalyse = 14,
                            CategoryId = 1,
                            Nom = "PLG"
                        },
                        new
                        {
                            IdTypeAnalyse = 15,
                            CategoryId = 1,
                            Nom = "AP"
                        },
                        new
                        {
                            IdTypeAnalyse = 16,
                            CategoryId = 2,
                            Nom = "FSC num."
                        },
                        new
                        {
                            IdTypeAnalyse = 17,
                            CategoryId = 2,
                            Nom = "Plt"
                        },
                        new
                        {
                            IdTypeAnalyse = 18,
                            CategoryId = 2,
                            Nom = "Micro"
                        },
                        new
                        {
                            IdTypeAnalyse = 19,
                            CategoryId = 2,
                            Nom = "VS"
                        },
                        new
                        {
                            IdTypeAnalyse = 20,
                            CategoryId = 2,
                            Nom = "FSC diff."
                        },
                        new
                        {
                            IdTypeAnalyse = 21,
                            CategoryId = 3,
                            Nom = "ALP"
                        },
                        new
                        {
                            IdTypeAnalyse = 22,
                            CategoryId = 3,
                            Nom = "ALT"
                        },
                        new
                        {
                            IdTypeAnalyse = 23,
                            CategoryId = 3,
                            Nom = "Amylase"
                        },
                        new
                        {
                            IdTypeAnalyse = 24,
                            CategoryId = 3,
                            Nom = "AST"
                        },
                        new
                        {
                            IdTypeAnalyse = 25,
                            CategoryId = 3,
                            Nom = "GGT"
                        },
                        new
                        {
                            IdTypeAnalyse = 26,
                            CategoryId = 3,
                            Nom = "Lipase"
                        },
                        new
                        {
                            IdTypeAnalyse = 27,
                            CategoryId = 3,
                            Nom = "Créatinine sérique"
                        },
                        new
                        {
                            IdTypeAnalyse = 28,
                            CategoryId = 3,
                            Nom = "Créatinine urinaire"
                        },
                        new
                        {
                            IdTypeAnalyse = 29,
                            CategoryId = 3,
                            Nom = "Acide urique"
                        },
                        new
                        {
                            IdTypeAnalyse = 30,
                            CategoryId = 3,
                            Nom = "Urée"
                        },
                        new
                        {
                            IdTypeAnalyse = 31,
                            CategoryId = 3,
                            Nom = "Clairance de la créatinine"
                        },
                        new
                        {
                            IdTypeAnalyse = 32,
                            CategoryId = 3,
                            Nom = "Bilirubine totale"
                        },
                        new
                        {
                            IdTypeAnalyse = 33,
                            CategoryId = 3,
                            Nom = "Bilirubine conjuguée"
                        },
                        new
                        {
                            IdTypeAnalyse = 34,
                            CategoryId = 3,
                            Nom = "Troponine"
                        },
                        new
                        {
                            IdTypeAnalyse = 35,
                            CategoryId = 3,
                            Nom = "Protéine C-réactive"
                        },
                        new
                        {
                            IdTypeAnalyse = 36,
                            CategoryId = 3,
                            Nom = "BNP"
                        },
                        new
                        {
                            IdTypeAnalyse = 37,
                            CategoryId = 3,
                            Nom = "Potassium"
                        },
                        new
                        {
                            IdTypeAnalyse = 38,
                            CategoryId = 3,
                            Nom = "Sodium"
                        },
                        new
                        {
                            IdTypeAnalyse = 39,
                            CategoryId = 3,
                            Nom = "Chlorure"
                        },
                        new
                        {
                            IdTypeAnalyse = 40,
                            CategoryId = 3,
                            Nom = "HCO3"
                        },
                        new
                        {
                            IdTypeAnalyse = 41,
                            CategoryId = 3,
                            Nom = "pH"
                        },
                        new
                        {
                            IdTypeAnalyse = 42,
                            CategoryId = 3,
                            Nom = "pCO2"
                        },
                        new
                        {
                            IdTypeAnalyse = 43,
                            CategoryId = 3,
                            Nom = "pO2"
                        },
                        new
                        {
                            IdTypeAnalyse = 44,
                            CategoryId = 3,
                            Nom = "Excès de bases"
                        },
                        new
                        {
                            IdTypeAnalyse = 45,
                            CategoryId = 3,
                            Nom = "Glucose"
                        },
                        new
                        {
                            IdTypeAnalyse = 46,
                            CategoryId = 3,
                            Nom = "Triglycérides"
                        },
                        new
                        {
                            IdTypeAnalyse = 47,
                            CategoryId = 3,
                            Nom = "HDL-cholestérol"
                        },
                        new
                        {
                            IdTypeAnalyse = 48,
                            CategoryId = 3,
                            Nom = "LDL-cholestérol"
                        },
                        new
                        {
                            IdTypeAnalyse = 49,
                            CategoryId = 3,
                            Nom = "Cholestérol total"
                        },
                        new
                        {
                            IdTypeAnalyse = 50,
                            CategoryId = 3,
                            Nom = "Protéines totales"
                        },
                        new
                        {
                            IdTypeAnalyse = 51,
                            CategoryId = 3,
                            Nom = "Albumine"
                        },
                        new
                        {
                            IdTypeAnalyse = 52,
                            CategoryId = 3,
                            Nom = "b-HCG qualitatif"
                        },
                        new
                        {
                            IdTypeAnalyse = 53,
                            CategoryId = 3,
                            Nom = "Éthanol"
                        },
                        new
                        {
                            IdTypeAnalyse = 54,
                            CategoryId = 3,
                            Nom = "Osmolarité urinaire"
                        },
                        new
                        {
                            IdTypeAnalyse = 55,
                            CategoryId = 3,
                            Nom = "Osmolarité sérique"
                        },
                        new
                        {
                            IdTypeAnalyse = 56,
                            CategoryId = 3,
                            Nom = "Drogues de rue"
                        },
                        new
                        {
                            IdTypeAnalyse = 57,
                            CategoryId = 3,
                            Nom = "Microscopie urinaire"
                        },
                        new
                        {
                            IdTypeAnalyse = 58,
                            CategoryId = 4,
                            Nom = "Glucose"
                        },
                        new
                        {
                            IdTypeAnalyse = 59,
                            CategoryId = 4,
                            Nom = "Corps cétoniques"
                        },
                        new
                        {
                            IdTypeAnalyse = 60,
                            CategoryId = 4,
                            Nom = "Densité"
                        },
                        new
                        {
                            IdTypeAnalyse = 61,
                            CategoryId = 4,
                            Nom = "Sang"
                        },
                        new
                        {
                            IdTypeAnalyse = 62,
                            CategoryId = 4,
                            Nom = "pH"
                        },
                        new
                        {
                            IdTypeAnalyse = 63,
                            CategoryId = 4,
                            Nom = "Protéines"
                        },
                        new
                        {
                            IdTypeAnalyse = 64,
                            CategoryId = 4,
                            Nom = "Leucocytes"
                        },
                        new
                        {
                            IdTypeAnalyse = 65,
                            CategoryId = 4,
                            Nom = "Nitrites"
                        },
                        new
                        {
                            IdTypeAnalyse = 66,
                            CategoryId = 4,
                            Nom = "Bilirubine"
                        },
                        new
                        {
                            IdTypeAnalyse = 67,
                            CategoryId = 4,
                            Nom = "Urobilinogène"
                        });
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.TypeValeur", b =>
                {
                    b.Property<int>("IdTypeValeur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeValeur"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeAnalyseId")
                        .HasColumnType("int");

                    b.HasKey("IdTypeValeur");

                    b.HasIndex("TypeAnalyseId");

                    b.ToTable("TypeValeurs");

                    b.HasData(
                        new
                        {
                            IdTypeValeur = 1,
                            Nom = "TS",
                            Reference = "4-8 min",
                            TypeAnalyseId = 1
                        },
                        new
                        {
                            IdTypeValeur = 2,
                            Nom = "To",
                            Reference = "EPI: 80-150 secs,ADP: 60-100 secs",
                            TypeAnalyseId = 2
                        },
                        new
                        {
                            IdTypeValeur = 3,
                            Nom = "PTT",
                            Reference = "22.0-40.0 secs",
                            TypeAnalyseId = 3
                        },
                        new
                        {
                            IdTypeValeur = 4,
                            Nom = "PT",
                            Reference = "11.0-14.0 secs",
                            TypeAnalyseId = 4
                        },
                        new
                        {
                            IdTypeValeur = 5,
                            Nom = "TT",
                            Reference = "≤ 24.0 secs",
                            TypeAnalyseId = 5
                        },
                        new
                        {
                            IdTypeValeur = 6,
                            Nom = "Fibrinogène",
                            Reference = "2.0-4.0 g/L",
                            TypeAnalyseId = 6
                        },
                        new
                        {
                            IdTypeValeur = 7,
                            Nom = "Facteur",
                            Reference = "50-150 %",
                            TypeAnalyseId = 7
                        },
                        new
                        {
                            IdTypeValeur = 8,
                            Nom = "D-dimères",
                            Reference = "<0.50 µg/mL",
                            TypeAnalyseId = 8
                        },
                        new
                        {
                            IdTypeValeur = 9,
                            Nom = "fVW",
                            Reference = "50-160 %",
                            TypeAnalyseId = 9
                        },
                        new
                        {
                            IdTypeValeur = 10,
                            Nom = "LA Screen",
                            Reference = "≥1.20",
                            TypeAnalyseId = 10
                        },
                        new
                        {
                            IdTypeValeur = 11,
                            Nom = "Anti-Xa",
                            Reference = "0.50-1.00 Ul-mL",
                            TypeAnalyseId = 11
                        },
                        new
                        {
                            IdTypeValeur = 12,
                            Nom = "Prt C",
                            Reference = "70-130 %",
                            TypeAnalyseId = 12
                        },
                        new
                        {
                            IdTypeValeur = 13,
                            Nom = "Prt S",
                            Reference = "70-130 %",
                            TypeAnalyseId = 13
                        },
                        new
                        {
                            IdTypeValeur = 14,
                            Nom = "PLG",
                            Reference = "80-120 %",
                            TypeAnalyseId = 14
                        },
                        new
                        {
                            IdTypeValeur = 15,
                            Nom = "AP",
                            Reference = "80-120 %",
                            TypeAnalyseId = 15
                        },
                        new
                        {
                            IdTypeValeur = 62,
                            Nom = "GB",
                            Reference = "4.8-10.8 X 10⁹/L",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 63,
                            Nom = "GR",
                            Reference = "♂ : 4.4-6.0 X 10¹²/L,♀ : 4.0-5.6 X 10¹²/L",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 64,
                            Nom = "Hb",
                            Reference = "♂ : 134-170 g/L,♀ : 117-157 g/L",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 65,
                            Nom = "Ht",
                            Reference = "♂ : 0.420-0.500 g/L,♀ : 0.370-0.470 L/L",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 66,
                            Nom = "VMC",
                            Reference = "81-99 fL",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 67,
                            Nom = "TGMH",
                            Reference = "27-33 pg",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 68,
                            Nom = "CGMH",
                            Reference = "323-365 g/L",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 69,
                            Nom = "IDC",
                            Reference = "12.7-16.0 %, 37.6-50.3 fL",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 70,
                            Nom = "Plt",
                            Reference = "140-400 X 10⁹/L",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 71,
                            Nom = "VMP",
                            Reference = "7.4-10.4 fL",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 72,
                            Nom = "IDP",
                            Reference = "15-17 %",
                            TypeAnalyseId = 16
                        },
                        new
                        {
                            IdTypeValeur = 73,
                            Nom = "Plt",
                            Reference = "140-400 X 10⁹/L",
                            TypeAnalyseId = 17
                        },
                        new
                        {
                            IdTypeValeur = 74,
                            Nom = "Micro",
                            Reference = "♂ : 0.420-0.500 g/L,♀ : 0.370-0.470 L/L",
                            TypeAnalyseId = 18
                        },
                        new
                        {
                            IdTypeValeur = 75,
                            Nom = "VS",
                            Reference = "♂ : 0-10 mm/h,♀ : 0.20 mm/h",
                            TypeAnalyseId = 19
                        },
                        new
                        {
                            IdTypeValeur = 76,
                            Nom = "NEUTRO",
                            Reference = "50-70 %,2.2-6.5 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 77,
                            Nom = "STAB",
                            Reference = "0-80 %,0.05-0.10 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 78,
                            Nom = "EOSINO",
                            Reference = "0.01-4 %,0.02-0.440 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 79,
                            Nom = "BASO",
                            Reference = "0.01-2 %,0.00-0.15 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 80,
                            Nom = "LYMPHO",
                            Reference = "17-42 %,1.2-3.6 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 81,
                            Nom = "MONO",
                            Reference = "1-12 %,0.08-0.870 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 82,
                            Nom = "LY.AT.",
                            Reference = "0-5 %,< 1.0 X 10⁹/L",
                            TypeAnalyseId = 20
                        },
                        new
                        {
                            IdTypeValeur = 16,
                            Nom = "ALP",
                            Reference = "<100 U/L *selon l'âge du patient",
                            TypeAnalyseId = 21
                        },
                        new
                        {
                            IdTypeValeur = 17,
                            Nom = "ALT",
                            Reference = "0-37 U/L",
                            TypeAnalyseId = 22
                        },
                        new
                        {
                            IdTypeValeur = 18,
                            Nom = "Amylase",
                            Reference = "<130 U/L",
                            TypeAnalyseId = 23
                        },
                        new
                        {
                            IdTypeValeur = 19,
                            Nom = "AST",
                            Reference = "5-34 U/L",
                            TypeAnalyseId = 24
                        },
                        new
                        {
                            IdTypeValeur = 20,
                            Nom = "GGT",
                            Reference = "<40 U/L",
                            TypeAnalyseId = 25
                        },
                        new
                        {
                            IdTypeValeur = 21,
                            Nom = "Lipase",
                            Reference = "<200 U/L",
                            TypeAnalyseId = 26
                        },
                        new
                        {
                            IdTypeValeur = 22,
                            Nom = "Créatinine sérique",
                            Reference = "57-92 umol/L",
                            TypeAnalyseId = 27
                        },
                        new
                        {
                            IdTypeValeur = 23,
                            Nom = "Créatinine urinaire",
                            Reference = "9-18 mmol/24h",
                            TypeAnalyseId = 28
                        },
                        new
                        {
                            IdTypeValeur = 24,
                            Nom = "Acide urique",
                            Reference = "210-460 umol/L",
                            TypeAnalyseId = 29
                        },
                        new
                        {
                            IdTypeValeur = 25,
                            Nom = "Urée",
                            Reference = "2.5-6.4 mmol/L",
                            TypeAnalyseId = 30
                        },
                        new
                        {
                            IdTypeValeur = 26,
                            Nom = "Clairance de la créatinine",
                            Reference = "1-3 mL/s",
                            TypeAnalyseId = 31
                        },
                        new
                        {
                            IdTypeValeur = 27,
                            Nom = "Bilirubine totale",
                            Reference = "3.4 - 22 umol/L",
                            TypeAnalyseId = 32
                        },
                        new
                        {
                            IdTypeValeur = 28,
                            Nom = "Bilirubine conjuguée",
                            Reference = "1.7 - 5 umol/L",
                            TypeAnalyseId = 33
                        },
                        new
                        {
                            IdTypeValeur = 29,
                            Nom = "Troponine",
                            Reference = "< 0.4ug/L",
                            TypeAnalyseId = 34
                        },
                        new
                        {
                            IdTypeValeur = 30,
                            Nom = "Protéine C-réactive",
                            Reference = "< 10mg/L",
                            TypeAnalyseId = 35
                        },
                        new
                        {
                            IdTypeValeur = 31,
                            Nom = "BNP",
                            Reference = "< 100pg/mL",
                            TypeAnalyseId = 36
                        },
                        new
                        {
                            IdTypeValeur = 32,
                            Nom = "Potassium",
                            Reference = "3.5-5 mmol/L",
                            TypeAnalyseId = 37
                        },
                        new
                        {
                            IdTypeValeur = 33,
                            Nom = "Sodium",
                            Reference = "135-145 mmol/L",
                            TypeAnalyseId = 38
                        },
                        new
                        {
                            IdTypeValeur = 34,
                            Nom = "Chlorure",
                            Reference = "98-108 mmol/L",
                            TypeAnalyseId = 39
                        },
                        new
                        {
                            IdTypeValeur = 35,
                            Nom = "HCO3",
                            Reference = "22-28 mmol/L",
                            TypeAnalyseId = 40
                        },
                        new
                        {
                            IdTypeValeur = 36,
                            Nom = "pH",
                            Reference = "7.35-7.45",
                            TypeAnalyseId = 41
                        },
                        new
                        {
                            IdTypeValeur = 37,
                            Nom = "pCO2",
                            Reference = "35-45 mmHg",
                            TypeAnalyseId = 42
                        },
                        new
                        {
                            IdTypeValeur = 38,
                            Nom = "pO2",
                            Reference = "80-100 mmHg",
                            TypeAnalyseId = 43
                        },
                        new
                        {
                            IdTypeValeur = 39,
                            Nom = "Excès de bases",
                            Reference = "-2 à +2 mmol/L",
                            TypeAnalyseId = 44
                        },
                        new
                        {
                            IdTypeValeur = 40,
                            Nom = "Glucose",
                            Reference = "Aci3.5-5",
                            TypeAnalyseId = 45
                        },
                        new
                        {
                            IdTypeValeur = 41,
                            Nom = "Triglycérides",
                            Reference = "<1.7 mmol/L",
                            TypeAnalyseId = 46
                        },
                        new
                        {
                            IdTypeValeur = 42,
                            Nom = "HDL-cholestérol",
                            Reference = ">1.0 mmol/L",
                            TypeAnalyseId = 47
                        },
                        new
                        {
                            IdTypeValeur = 43,
                            Nom = "LDL-cholestérol",
                            Reference = "<2.5 mmol/L",
                            TypeAnalyseId = 48
                        },
                        new
                        {
                            IdTypeValeur = 44,
                            Nom = "Cholestérol total",
                            Reference = "<5.2 mmol/L",
                            TypeAnalyseId = 49
                        },
                        new
                        {
                            IdTypeValeur = 45,
                            Nom = "Protéines totales",
                            Reference = "60-80 g/L",
                            TypeAnalyseId = 50
                        },
                        new
                        {
                            IdTypeValeur = 46,
                            Nom = "Albumine",
                            Reference = "35-50 g/L",
                            TypeAnalyseId = 51
                        },
                        new
                        {
                            IdTypeValeur = 47,
                            Nom = "b-HCG qualitatif",
                            Reference = "Négatif",
                            TypeAnalyseId = 52
                        },
                        new
                        {
                            IdTypeValeur = 48,
                            Nom = "Drogues de rue",
                            Reference = "Négatif",
                            TypeAnalyseId = 56
                        },
                        new
                        {
                            IdTypeValeur = 49,
                            Nom = "Éthanol",
                            Reference = "0 mmol/L",
                            TypeAnalyseId = 53
                        },
                        new
                        {
                            IdTypeValeur = 50,
                            Nom = "Osmolarité urinaire",
                            Reference = "540 mosmol/kg",
                            TypeAnalyseId = 54
                        },
                        new
                        {
                            IdTypeValeur = 51,
                            Nom = "Osmolarité sérique",
                            Reference = "290 mosmol/kg",
                            TypeAnalyseId = 55
                        },
                        new
                        {
                            IdTypeValeur = 52,
                            Nom = "Glucose",
                            Reference = "Négatif",
                            TypeAnalyseId = 58
                        },
                        new
                        {
                            IdTypeValeur = 53,
                            Nom = "Corps cétoniques",
                            Reference = "Négatif",
                            TypeAnalyseId = 59
                        },
                        new
                        {
                            IdTypeValeur = 54,
                            Nom = "Densité",
                            Reference = "1.005-1.030",
                            TypeAnalyseId = 60
                        },
                        new
                        {
                            IdTypeValeur = 55,
                            Nom = "Sang",
                            Reference = "Négatif",
                            TypeAnalyseId = 61
                        },
                        new
                        {
                            IdTypeValeur = 56,
                            Nom = "pH",
                            Reference = "4-8",
                            TypeAnalyseId = 62
                        },
                        new
                        {
                            IdTypeValeur = 57,
                            Nom = "Protéines",
                            Reference = "Négatif",
                            TypeAnalyseId = 63
                        },
                        new
                        {
                            IdTypeValeur = 58,
                            Nom = "Leucocytes",
                            Reference = "Négatif",
                            TypeAnalyseId = 64
                        },
                        new
                        {
                            IdTypeValeur = 59,
                            Nom = "Nitrites",
                            Reference = "Négatif",
                            TypeAnalyseId = 65
                        },
                        new
                        {
                            IdTypeValeur = 60,
                            Nom = "Bilirubine",
                            Reference = "Négatif",
                            TypeAnalyseId = 66
                        },
                        new
                        {
                            IdTypeValeur = 61,
                            Nom = "Urobilinogène",
                            Reference = "Négatif",
                            TypeAnalyseId = 67
                        });
                });

            modelBuilder.Entity("RequeteAnalyseTypeAnalyse", b =>
                {
                    b.Property<int>("LstTypeAnalyseIdTypeAnalyse")
                        .HasColumnType("int");

                    b.Property<int>("RequeteAnalysesIdRequete")
                        .HasColumnType("int");

                    b.HasKey("LstTypeAnalyseIdTypeAnalyse", "RequeteAnalysesIdRequete");

                    b.HasIndex("RequeteAnalysesIdRequete");

                    b.ToTable("RequeteAnalyseTypeAnalyse");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.RequeteAnalyse", b =>
                {
                    b.HasOne("API_AnalyseSanguine.Models.Dossier", "Dossier")
                        .WithMany("LstRequetes")
                        .HasForeignKey("DossierIdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AnalyseSanguine.Models.Medecin", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinIdMedecin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");

                    b.Navigation("Medecin");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.ResultatAnalyse", b =>
                {
                    b.HasOne("API_AnalyseSanguine.Models.RequeteAnalyse", "RequeteAnalyse")
                        .WithMany("LstResultats")
                        .HasForeignKey("RequeteAnalyseIdRequete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AnalyseSanguine.Models.TypeValeur", "TypeValeur")
                        .WithMany()
                        .HasForeignKey("TypeValeurIdTypeValeur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequeteAnalyse");

                    b.Navigation("TypeValeur");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.TypeAnalyse", b =>
                {
                    b.HasOne("API_AnalyseSanguine.Models.Category", "Category")
                        .WithMany("TypeAnalyseList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.TypeValeur", b =>
                {
                    b.HasOne("API_AnalyseSanguine.Models.TypeAnalyse", "TypeAnalyse")
                        .WithMany("LstValeurs")
                        .HasForeignKey("TypeAnalyseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeAnalyse");
                });

            modelBuilder.Entity("RequeteAnalyseTypeAnalyse", b =>
                {
                    b.HasOne("API_AnalyseSanguine.Models.TypeAnalyse", null)
                        .WithMany()
                        .HasForeignKey("LstTypeAnalyseIdTypeAnalyse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AnalyseSanguine.Models.RequeteAnalyse", null)
                        .WithMany()
                        .HasForeignKey("RequeteAnalysesIdRequete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.Category", b =>
                {
                    b.Navigation("TypeAnalyseList");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.Dossier", b =>
                {
                    b.Navigation("LstRequetes");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.RequeteAnalyse", b =>
                {
                    b.Navigation("LstResultats");
                });

            modelBuilder.Entity("API_AnalyseSanguine.Models.TypeAnalyse", b =>
                {
                    b.Navigation("LstValeurs");
                });
#pragma warning restore 612, 618
        }
    }
}
